In [3]:
import numpy as np


Задание 1 по теме "Вычисления с помощью Numpy"

In [10]:
a=np.array([[1,6],[2,8],[3,11],[3,10],[1,7]])

In [11]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [12]:
a.shape

(5, 2)

In [13]:
mean_a=a.mean(axis=0)

In [14]:
mean_a

array([2. , 8.4])

Задание 2 по теме "Вычисления с помощью Numpy"

In [19]:
a_centered=np.subtract(a,mean_a)

In [20]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3 по теме "Вычисления с помощью Numpy"

In [27]:
a_centered_sp=np.dot(a_centered[:,0],a_centered[:,1])

In [28]:
a_centered_sp

8.0

In [29]:
a_centered_sp/(a_centered.shape[0]-1)

2.0

Задание 4 по теме "Вычисления с помощью Numpy"

In [33]:
aa=a.transpose()

In [36]:
np.cov(aa[0,:],aa[1,:])

array([[1. , 2. ],
       [2. , 4.3]])

Задание 1 по теме "Работа с данными в Pandas"


In [38]:
import pandas as pd

In [40]:
authors=pd.DataFrame({'author_id':[1,2,3], 'author_name': ['Тургенев', 'Чехов','Островский']},
                     columns=['author_id','author_name'])

In [41]:
book=pd.DataFrame({'author_id':[1,1,1,2,2,3,3], 'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 
                                                             'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                   'price': [450,300, 350, 500,450,370, 290]})

In [43]:
authors.shape

(3, 2)

In [44]:
book.shape

(7, 3)

Задание 2 по теме "Работа с данными в Pandas"

In [45]:
authors_price=pd.merge(authors,book, on='author_id', how='inner')

In [46]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290